version: '3.9'

services:
  currency-tracker:
    build: 
      context: .
      target: dev
    entrypoint: ["air", "-d"]
    links:
      - currency-tracker-db
    environment:
      - 'POSTGRES_HOST=currency-tracker-db'
      - 'POSTGRES_PORT=5432'
      - 'POSTGRES_DATABASE=${POSTGRES_DATABASE}'
      - 'POSTGRES_PASSWORD=${POSTGRES_PASSWORD}'
      - 'POSTGRES_USER=${POSTGRES_USER}'
      - 'PROJ_NAME=${PROJ_NAME}'
      - 'PROJ_ENV=${PROJ_ENV}'

    ports:
      - '8080:8080'
      - '2345:2345'
    volumes:
      - .:/usr/github.com/isaias-dgr/currency-tracker:rw

  currency-tracker-db:
    image: postgres:latest
    ports:
      - '5432:5432'
    environment:
      - 'POSTGRES_DATABASE=${POSTGRES_DATABASE}'
      - 'POSTGRES_USER=${POSTGRES_USER}'
      - 'POSTGRES_PASSWORD=${POSTGRES_PASSWORD}'
    restart: unless-stopped
