version: '3.9'

services:
  ms-todo:
    build: 
      context: .
      target: dev
    entrypoint: ["air", "-d"]
    container_name: dev_todo
    links:
      - ms-todo-db
    environment:
      - 'MYSQL_HOST=ms-todo-db'
      - 'MYSQL_PORT=3306'
      - 'MYSQL_DATABASE=${MYSQL_DATABASE}'
      - 'MYSQL_PASSWORD=${MYSQL_PASSWORD}'
      - 'MYSQL_USER=${MYSQL_USER}'
      - 'PROJ_NAME=${PROJ_NAME}'
      - 'PROJ_ENV=${PROJ_ENV}'

    ports:
      - '8080:8080'
      - '2345:2345'
    volumes:
      - .:/usr/github.com/isaias-dgr/todo:rw

  ms-todo-db:
    image: mysql
    command: mysqld --user=root
    ports:
      - '3306:3306'
    environment:
      - 'MYSQL_DATABASE=${MYSQL_DATABASE}'
      - 'MYSQL_USER=${MYSQL_USER}'
      - 'MYSQL_PASSWORD=${MYSQL_PASSWORD}'
      - 'MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}'
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 5s
      retries: 10

  adminer:
    image: adminer
    container_name: adminer_db_dev_todo
    restart: always
    depends_on:
      - ms-todo-db
    ports:
      - '8081:8080'
