openapi: 3.0.0
info:
  title: API documentation
  version: 1.0.0
servers:
  - url: http://localhost:8080/
tags:
  - name: Currency
paths:
  /currencies/{code}:
    $ref: './resources/currency.yaml#/CurrencyPathWithID'

components:
  schemas:
    currency:
      $ref: './schemas/currency_schema.yaml'
